import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      data-theme="system"
      // className={`

      //   [&::-webkit-scrollbar]:w-1.5
      // [&::-webkit-scrollbar-track]:bg-gray-100
      // [&::-webkit-scrollbar-thumb]:bg-gray-300
      //   [&::-webkit-scrollbar-thumb]:cursor-point
      // dark:[&::-webkit-scrollbar-track]:bg-neutral-700
      // dark:[&::-webkit-scrollbar-thumb]:bg-neutral-500
      // `}
      //
      suppressHydrationWarning
    >
      {children}
    </main>
  );
}
